#spring:
#  datasource:
#    url: jdbc:sqlserver://transitgo.database.windows.net:1433;database=transitGO;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: transitgo
#    password: mora@123
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect : org.hibernate.dialect.SQLServer2012Dialect
#
#server:
#  port: 9191
#
